name: Deploy hexo to dev branch
on:
  push:
    branches:
      - "main"
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies using Yarn
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Check Yarn and Node version
        run: |
          echo "Node version is `node -v`"
          echo "Yarn version is `yarn -v`"

      - name: Configure Git and Update Repo URL
        run: |
          git config --global user.name "Olint"
          git config --global user.email "1@qq.com"
          # 修改 _config.yml 中的仓库地址以支持 HTTPS
          sed -i'' "s~git@github.com:~https://${{ secrets.GH_TOKEN }}@github.com/~" _config.yml

      - name: Clean, Build, and Deploy
        run: |
          rm -rf .deploy_git  # 删除之前的 deploy 文件夹，确保干净的构建环境
          yarn clean
          yarn build
          yarn deploy
